import React from "react";
import { createRoot } from "react-dom/client";
import "./ui/theme/base.css";
import "./ui/theme/design-platform.css";
import "./ui/theme/gradient-shadow-text.css";
import "./ui/theme/scrollbar.css";
import "./ui/theme/corner-shape.css";
import "./ui/shared/base.css";
import "./ui/shared/design-platform.css";
import "./ui/shared/gradient-shadow-text.css";
import "./ui/shared/focus.css";
import "./ui/shared/shiki.css";
import { TelemetryBoundary } from "./TelemetryBoundary.tsx";
import { PiApp } from "./PiApp.tsx";
import { installThemePreference } from "./ui/theme/preference.ts";
import { installLocalePreference } from "./ui/locale/preference.ts";

installThemePreference();
installLocalePreference();
const root = document.getElementById("root");
if (!root) throw new Error("Missing #root");
createRoot(root).render(<TelemetryBoundary><PiApp /></TelemetryBoundary>);
